# Time-stamp: <2017-07-12 16:43:01 cp983411>

all: hrf dmtx

# generate convolved regressors from event files
hrf:   
	python events2hrf.py -t 2 -n 282 -i inputs/1_bottomup.csv -o outputs/1_bottomup_reg.csv
	python events2hrf.py -t 2 -n 282 -i inputs/1_f0.csv -o outputs/1_f0_reg.csv
	python events2hrf.py -t 2 -n 282 -i inputs/1_freq.csv -o outputs/1_freq_reg.csv
	python events2hrf.py -t 2 -n 282 -i inputs/1_leftcorner.csv -o outputs/1_leftcorner_reg.csv
	python events2hrf.py -t 2 -n 282 -i inputs/1_mwe.csv -o outputs/1_mwe_reg.csv
	python events2hrf.py -t 2 -n 282 -i inputs/1_rms.csv -o outputs/1_rms_reg.csv
	python events2hrf.py -t 2 -n 282 -i inputs/1_wordrate.csv -o outputs/1_wordrate_reg.csv
	python events2hrf.py -t 2 -n 298 -i inputs/2_bottomup.csv -o outputs/2_bottomup_reg.csv
	python events2hrf.py -t 2 -n 298 -i inputs/2_f0.csv -o outputs/2_f0_reg.csv
	python events2hrf.py -t 2 -n 298 -i inputs/2_freq.csv -o outputs/2_freq_reg.csv
	python events2hrf.py -t 2 -n 298 -i inputs/2_leftcorner.csv -o outputs/2_leftcorner_reg.csv
	python events2hrf.py -t 2 -n 298 -i inputs/2_mwe.csv -o outputs/2_mwe_reg.csv
	python events2hrf.py -t 2 -n 298 -i inputs/2_rms.csv -o outputs/2_rms_reg.csv
	python events2hrf.py -t 2 -n 298 -i inputs/2_wordrate.csv -o outputs/2_wordrate_reg.csv
	python events2hrf.py -t 2 -n 340 -i inputs/3_bottomup.csv -o outputs/3_bottomup_reg.csv
	python events2hrf.py -t 2 -n 340 -i inputs/3_f0.csv -o outputs/3_f0_reg.csv
	python events2hrf.py -t 2 -n 340 -i inputs/3_freq.csv -o outputs/3_freq_reg.csv
	python events2hrf.py -t 2 -n 340 -i inputs/3_leftcorner.csv -o outputs/3_leftcorner_reg.csv
	python events2hrf.py -t 2 -n 340 -i inputs/3_mwe.csv -o outputs/3_mwe_reg.csv
	python events2hrf.py -t 2 -n 340 -i inputs/3_rms.csv -o outputs/3_rms_reg.csv
	python events2hrf.py -t 2 -n 340 -i inputs/3_wordrate.csv -o outputs/3_wordrate_reg.csv
	python events2hrf.py -t 2 -n 303 -i inputs/4_bottomup.csv -o outputs/4_bottomup_reg.csv
	python events2hrf.py -t 2 -n 303 -i inputs/4_f0.csv -o outputs/4_f0_reg.csv
	python events2hrf.py -t 2 -n 303 -i inputs/4_freq.csv -o outputs/4_freq_reg.csv
	python events2hrf.py -t 2 -n 303 -i inputs/4_leftcorner.csv -o outputs/4_leftcorner_reg.csv
	python events2hrf.py -t 2 -n 303 -i inputs/4_mwe.csv -o outputs/4_mwe_reg.csv
	python events2hrf.py -t 2 -n 303 -i inputs/4_rms.csv -o outputs/4_rms_reg.csv
	python events2hrf.py -t 2 -n 303 -i inputs/4_wordrate.csv -o outputs/4_wordrate_reg.csv
	python events2hrf.py -t 2 -n 265 -i inputs/5_bottomup.csv -o outputs/5_bottomup_reg.csv
	python events2hrf.py -t 2 -n 265 -i inputs/5_f0.csv -o outputs/5_f0_reg.csv
	python events2hrf.py -t 2 -n 265 -i inputs/5_freq.csv -o outputs/5_freq_reg.csv
	python events2hrf.py -t 2 -n 265 -i inputs/5_leftcorner.csv -o outputs/5_leftcorner_reg.csv
	python events2hrf.py -t 2 -n 265 -i inputs/5_mwe.csv -o outputs/5_mwe_reg.csv
	python events2hrf.py -t 2 -n 265 -i inputs/5_rms.csv -o outputs/5_rms_reg.csv
	python events2hrf.py -t 2 -n 265 -i inputs/5_wordrate.csv -o outputs/5_wordrate_reg.csv
	python events2hrf.py -t 2 -n 343 -i inputs/6_bottomup.csv -o outputs/6_bottomup_reg.csv
	python events2hrf.py -t 2 -n 343 -i inputs/6_f0.csv -o outputs/6_f0_reg.csv
	python events2hrf.py -t 2 -n 343 -i inputs/6_freq.csv -o outputs/6_freq_reg.csv
	python events2hrf.py -t 2 -n 343 -i inputs/6_leftcorner.csv -o outputs/6_leftcorner_reg.csv
	python events2hrf.py -t 2 -n 343 -i inputs/6_mwe.csv -o outputs/6_mwe_reg.csv
	python events2hrf.py -t 2 -n 343 -i inputs/6_rms.csv -o outputs/6_rms_reg.csv
	python events2hrf.py -t 2 -n 343 -i inputs/6_wordrate.csv -o outputs/6_wordrate_reg.csv
	python events2hrf.py -t 2 -n 325 -i inputs/7_bottomup.csv -o outputs/7_bottomup_reg.csv
	python events2hrf.py -t 2 -n 325 -i inputs/7_f0.csv -o outputs/7_f0_reg.csv
	python events2hrf.py -t 2 -n 325 -i inputs/7_freq.csv -o outputs/7_freq_reg.csv
	python events2hrf.py -t 2 -n 325 -i inputs/7_leftcorner.csv -o outputs/7_leftcorner_reg.csv
	python events2hrf.py -t 2 -n 325 -i inputs/7_mwe.csv -o outputs/7_mwe_reg.csv
	python events2hrf.py -t 2 -n 325 -i inputs/7_rms.csv -o outputs/7_rms_reg.csv
	python events2hrf.py -t 2 -n 325 -i inputs/7_wordrate.csv -o outputs/7_wordrate_reg.csv
	python events2hrf.py -t 2 -n 292 -i inputs/8_bottomup.csv -o outputs/8_bottomup_reg.csv
	python events2hrf.py -t 2 -n 292 -i inputs/8_f0.csv -o outputs/8_f0_reg.csv
	python events2hrf.py -t 2 -n 292 -i inputs/8_freq.csv -o outputs/8_freq_reg.csv
	python events2hrf.py -t 2 -n 292 -i inputs/8_leftcorner.csv -o outputs/8_leftcorner_reg.csv
	python events2hrf.py -t 2 -n 292 -i inputs/8_mwe.csv -o outputs/8_mwe_reg.csv
	python events2hrf.py -t 2 -n 292 -i inputs/8_rms.csv -o outputs/8_rms_reg.csv
	python events2hrf.py -t 2 -n 292 -i inputs/8_wordrate.csv -o outputs/8_wordrate_reg.csv
	python events2hrf.py -t 2 -n 368 -i inputs/9_bottomup.csv -o outputs/9_bottomup_reg.csv
	python events2hrf.py -t 2 -n 368 -i inputs/9_f0.csv -o outputs/9_f0_reg.csv
	python events2hrf.py -t 2 -n 368 -i inputs/9_freq.csv -o outputs/9_freq_reg.csv
	python events2hrf.py -t 2 -n 368 -i inputs/9_leftcorner.csv -o outputs/9_leftcorner_reg.csv
	python events2hrf.py -t 2 -n 368 -i inputs/9_mwe.csv -o outputs/9_mwe_reg.csv
	python events2hrf.py -t 2 -n 368 -i inputs/9_rms.csv -o outputs/9_rms_reg.csv
	python events2hrf.py -t 2 -n 368 -i inputs/9_wordrate.csv -o outputs/9_wordrate_reg.csv


dmtx: # generate the design matrices, in the 'outputs' subdirectory
	cd outputs; \
	for s in 1 2 3 4 5 6 7 8 9; do \
	echo '"bottomup","f0","freq","rms","mwe","wordrate"' > dmtx_$${s}.csv; \
	paste -d, $${s}_bottomup_reg.csv  $${s}_f0_reg.csv  $${s}_freq_reg.csv $${s}_rms_reg.csv $${s}_mwe_reg.csv  $${s}_wordrate_reg.csv >> dmtx_$${s}.csv; \
	done

check-correlations.html: check-correlations.Rmd 
	Rscript -e "rmarkdown::render('check-correlations.Rmd')" 

